FROM rust:1-slim-bookworm AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config libssl-dev protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY . .
RUN cargo build --locked --release -p dolos

FROM debian:12-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY .github/image/genesis /etc/genesis
COPY --from=builder /src/target/release/dolos /bin/dolos
RUN chmod +x /bin/dolos
RUN ln -s /bin/dolos /dolos
ENTRYPOINT [ "dolos" ]
